// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCyipFqdnGgLhYzRnuA6tdYVPNfJVE5M',
    appId: '1:453673442707:web:9edd5b4dd6c2be1ab51c66',
    messagingSenderId: '453673442707',
    projectId: 'fir-ce64a',
    authDomain: 'fir-ce64a.firebaseapp.com',
    storageBucket: 'fir-ce64a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pcYQ-cbpI-PKKcT_nyObagBmmaasIAI',
    appId: '1:453673442707:android:bd8bf6ccdc72f3f6b51c66',
    messagingSenderId: '453673442707',
    projectId: 'fir-ce64a',
    storageBucket: 'fir-ce64a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJafOlsmO-1-Gn3kfvP6KalOfEU4WZNkA',
    appId: '1:453673442707:ios:d60ab1c452e5324ab51c66',
    messagingSenderId: '453673442707',
    projectId: 'fir-ce64a',
    storageBucket: 'fir-ce64a.appspot.com',
    iosBundleId: 'com.example.censusdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJafOlsmO-1-Gn3kfvP6KalOfEU4WZNkA',
    appId: '1:453673442707:ios:5e6ec3af8a890e44b51c66',
    messagingSenderId: '453673442707',
    projectId: 'fir-ce64a',
    storageBucket: 'fir-ce64a.appspot.com',
    iosBundleId: 'com.example.censusdemo.RunnerTests',
  );
}
